//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESRI.SilverlightViewer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ESRI.SilverlightViewer.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dock to Bottom.
        /// </summary>
        internal static string TASKBAR_DOCK_BOTTOM {
            get {
                return ResourceManager.GetString("TASKBAR_DOCK_BOTTOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dock to Top.
        /// </summary>
        internal static string TASKBAR_DOCK_TOP {
            get {
                return ResourceManager.GetString("TASKBAR_DOCK_TOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floating.
        /// </summary>
        internal static string TASKBAR_FLOATING {
            get {
                return ResourceManager.GetString("TASKBAR_FLOATING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press &lt;CTRL&gt; + Click to Enable Floating.
        /// </summary>
        internal static string TASKBAR_TOOLTIP_DOCK {
            get {
                return ResourceManager.GetString("TASKBAR_TOOLTIP_DOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag or Press &lt;CTRL&gt; + Click to Dock.
        /// </summary>
        internal static string TASKBAR_TOOLTIP_FLOAT {
            get {
                return ResourceManager.GetString("TASKBAR_TOOLTIP_FLOAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Page.
        /// </summary>
        internal static string WIDGETBAR_NAVIGATE_BACK {
            get {
                return ResourceManager.GetString("WIDGETBAR_NAVIGATE_BACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Page.
        /// </summary>
        internal static string WIDGETBAR_NAVIGATE_NEXT {
            get {
                return ResourceManager.GetString("WIDGETBAR_NAVIGATE_NEXT", resourceCulture);
            }
        }
    }
}
